---
- name: set root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash('sha512')  }}"
  vars:
    root_password: "{{ root_passwords[inventory_hostname] | default('') }}"
  when: root_password != ''
