- name: assert | Test hostname
  ansible.builtin.assert:
    that:
      - hostname is defined
      - hostname is string
      - hostname is not none
    quiet: true

- name: assert | Test hostname_reboot
  ansible.builtin.assert:
    that:
      - hostname_reboot is defined
      - hostname_reboot is boolean
    quiet: true

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  notify:
    - Gather facts
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]

- name: Fix /etc/hosts removing the old hostname
  ansible.builtin.lineinfile:
        state: present
        dest: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        regexp: "^{{ ansible_default_ipv4.address }}"
  when:
    ansible_fqdn != inventory_hostname
