ipaclient_mkhomedir: true

ipaserver_domain: cross-ni.com
ipaserver_realm: CROSS-NI.COM
ipaserver_setup_dns: yes

ipaserver_dirsrv_cert_files: /etc/web_crt/crt.pem,/etc/web_crt/key.pem,/etc/web_crt/ca.pem
ipaserver_http_cert_files: /etc/web_crt/crt.pem,/etc/web_crt/key.pem,/etc/web_crt/ca.pem
ipaserver_dirsrv_pin: ""
ipaserver_http_pin: ""
ipaserver_no_pkinit: true
ipaserver_forwarders: 8.8.8.8,1.1.1.1

ipareplica_dirsrv_cert_files: "{{ ipaserver_dirsrv_cert_files }}"
ipareplica_http_cert_files: "{{ ipaserver_http_cert_files }}"
ipareplica_dirsrv_pin: ""
ipareplica_http_pin: ""
ipareplica_forwarders: 8.8.8.8,1.1.1.1
#ipareplica_dirsrv_cert_name:
#ipareplica_http_cert_name:
